version: '3'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    # Uncomment if you want to expose it outside container stack
    # ports:
    #   - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["app"]
    container_name: app
    ports:
      - "7860:7860"
    depends_on:
      - ollama
volumes:
  ollama_data:
