[tool.poetry]
name = "rag_langchain_ollama"
version = "0.0.0"
description = "An implementation of RAG with Ollama Embeddings & Model (Mistral) over sample TXT files via Langchain wrapped as a Gradio Application"
authors = ["Supreeth Kunder <kundersupreeth@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
langchain = "^0.2.1"
gradio = "^4.31.5"
pymongo = {extras = ["srv"], version = "^4.7.2"}
requests = "^2.32.2"
pydantic = "^2.7.1"
pydantic-settings = "^2.2.1"
llama-index = "^0.10.39"
pre-commit = "^3.7.1"

[tool.poetry.scripts]
app = "src.cli:run"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]
