[tool.poetry]
name = "genai-rag-langchain-ollama"
version = "0.0.0"
description = "An implementation of RAG with Ollama Embeddings & Model (Mistral) over sample TXT files via Langchain wrapped as a Gradio Application"
authors = ["Supreeth Kunder <kundersupreeth@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
langchain = "^0.1.16"
gradio = "^4.26.0"
pymongo = {extras = ["srv"], version = "^4.6.3"}
requests = "^2.31.0"
pydantic = "^2.7.0"
pydantic-settings = "^2.2.1"
llama-index = "^0.10.28"
pre-commit = "^3.7.0"

[tool.poetry.scripts]
app = "src.cli:run"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]
